# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ea6645a1d2108a18cd5aba715ee2ce3e00f203bdd43e22023406b458553eed8c4295897c7a0bf48ef756293a5431a9f419b51e0fa954651a1f2bf85790bdca63

test:
  secret_key_base: 651775d5eba5f1268b8bdbb040bec8716a3efa14653384e15802c32713f98b3a11b0cf149752023c8580507e5899c8c9541189297585c57b5c3f73d8739c307f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
